# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               "Git Note"
tagline:             'Day by day, in Everyway, I am getting better and better'
description:         'One a day'
url:                 https://dmjgr5.github.io
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              dcp
  url:               https://dmjgr5.github.io
  email:             dmjgr5@gmail.com

# Custom vars
version:             1.0.0

plugins:
  - jekyll-paginate
  - jemoji
  # - jekyll-sitemap

# Tag setting
#collections:
#  tags:
#    output: true
#    permalink: /tags/:path/

#defaults:
#  - scope:
#      path: ''
#      type: tags
#    values:
#      layout: tag

google_analytics:
  tracking_id: 'G-VEHRJDYDE5'


github:
  repo: 'https://github.com/dmjgr5/dmjgr5.github.io'

category_dir: category/
tag_dir: tag/

excerpt_separator: ""

  